# backend-deployment.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: domain-lookup-app
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_USER: aliz
  DB_NAME: alizdb

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: domain-lookup-app
type: Opaque
data:
  DB_PASSWORD: YWxpenRlc3Q=  # aliztest (base64 encoded)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: domain-lookup-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: spiritualguest/dns-backend:latest  # Replace with your image
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: domain-lookup-app
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP