# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: domain-lookup-app
type: Opaque
data:
  # Base64 encoded passwords
  # aliztest = YWxpenRlc3Q=
  # rootpassword = cm9vdHBhc3N3b3Jk
  DB_PASSWORD: YWxpenRlc3Q=
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: YWxpenRlc3Q=